"""Visual QA MCP chart MVP package."""

from .claim_graph import build_arrow_claim_graph, build_chart_claim_graph, build_geometry_claim_graph
from .contracts import (
    ArtifactPaths,
    AxisMapping,
    ChartDatasetCase,
    ClaimCheck,
    ClaimGap,
    ClaimGraph,
    EvidenceGraph,
    EvidenceGap,
    ExtractionProvenance,
    GeometryEvidenceGraph,
    ExtractedAxis,
    ExtractedBar,
    Finding,
    OverlayAnnotation,
    TickLabel,
    VerificationResult,
    VisualQaReport,
)
from .server import create_server
from .service import (
    build_claim_graph_from_spec,
    extract_chart_evidence_from_inputs,
    extract_geometry_evidence_from_inputs,
    load_claim_graph,
    load_evidence_graph,
    run_chart_verification,
    run_geometry_verification,
    run_chart_rules_from_graphs,
    write_verification_artifacts,
)

__all__ = [
    "ArtifactPaths",
    "AxisMapping",
    "build_claim_graph_from_spec",
    "build_chart_claim_graph",
    "build_arrow_claim_graph",
    "build_geometry_claim_graph",
    "ChartDatasetCase",
    "ClaimCheck",
    "ClaimGap",
    "ClaimGraph",
    "create_server",
    "EvidenceGraph",
    "EvidenceGap",
    "ExtractionProvenance",
    "extract_chart_evidence_from_inputs",
    "extract_geometry_evidence_from_inputs",
    "ExtractedAxis",
    "ExtractedBar",
    "Finding",
    "GeometryEvidenceGraph",
    "load_claim_graph",
    "load_evidence_graph",
    "OverlayAnnotation",
    "run_chart_verification",
    "run_geometry_verification",
    "run_chart_rules_from_graphs",
    "TickLabel",
    "VerificationResult",
    "VisualQaReport",
    "write_verification_artifacts",
]
